blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/ilim-cell/webbender/discussions
    about: Ask questions, share ideas, and get help with Webbender
  - name: 📖 Documentation
    url: https://github.com/ilim-cell/webbender/wiki
    about: Learn how to use and customize Webbender
