name: Triage

on:
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  triage-job:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Tools
        uses: ilim-cell/issuetools@v1
